export const NAVIGATION_CAMERA_V1_FIXTURE = Object.freeze({
  sourceRepository: "luizidebook/morro-de-sao-paulo-digital",
  sourceCommit: "60746fd7fed97b805758b37adfdbe3bad2582bfe",
  sourcePath: "js/navigation/navigationRuntime/navigation-route-runtime.js",
  camera: Object.freeze({
    minimumIntervalMs: 900,
    minimumMovementMeters: 1.5,
    minimumBearingDegrees: 2.5,
    smallChangeMovementMeters: 4,
    smallChangeBearingDegrees: 6,
    pitch: 68,
    defaultZoom: 19.1,
    nearZoom: 19.35,
    closeZoom: 19.55,
    forcedDurationMs: 900,
    normalDurationMs: 650,
    zoomDeltaThreshold: 0.05,
    easingSamples: Object.freeze([
      Object.freeze({ input: 0, output: 0 }),
      Object.freeze({ input: 0.25, output: 0.4375 }),
      Object.freeze({ input: 0.5, output: 0.75 }),
      Object.freeze({ input: 0.75, output: 0.9375 }),
      Object.freeze({ input: 1, output: 1 }),
    ]),
  }),
  hysteresis: Object.freeze({
    farToNearBelowMeters: 65,
    nearToCloseAtOrBelowMeters: 22,
    closeToNearAboveMeters: 38,
    nearToFarAboveMeters: 90,
  }),
  padding: Object.freeze({
    topRatio: 0.39,
    bottomRatio: 0.06,
    horizontalRatio: 0.06,
    horizontalMaxPx: 28,
    minimumWidth: 280,
    minimumHeight: 320,
  }),
  invariants: Object.freeze({
    retainPadding: false,
    essential: true,
    pollingWithoutVisualChangeRestartsCamera: false,
    staleVisualUpdatesAreIgnored: true,
    singleCameraOwner: true,
  }),
});
