export const morroV1SearchEnrichmentPart2 = [
  {
    category: "restaurants",
    name: "Barraca da Miriam",
    area: "praia",
    tags: ["bar", "petisco", "praia", "quiosque"],
  },
  {
    category: "restaurants",
    name: "O Casarão restaurante",
    area: "vila",
    tags: ["vila"],
  },
  {
    category: "restaurants",
    name: "Awa Mar",
    area: "praia",
    tags: ["4a_praia", "beach_club", "frutos do mar", "praia", "seafood"],
  },
  {
    category: "restaurants",
    name: "Restaurante Pôr do Sol",
    area: "caminho",
    tags: ["caminho", "regional"],
  },
  {
    category: "restaurants",
    name: "Restaurante da Piscina",
    area: "praia",
    tags: ["4a_praia", "frutos do mar", "praia", "seafood"],
  },
  {
    category: "restaurants",
    name: "Echoes Beach Club",
    area: "gamboa",
    tags: ["bar", "beach_club", "gamboa", "petisco"],
  },
  {
    category: "restaurants",
    name: "Restaurante Farol",
    area: "vila",
    tags: ["baiana", "regional", "vila"],
  },
  {
    category: "restaurants",
    name: "Sabores do Morro",
    area: "vila",
    tags: ["vila"],
  },
  {
    category: "hotels",
    name: "Hotel Fazenda Parque Praia Vila Guaiamu",
    area: "praia",
    tags: [
      "3a_praia",
      "charme",
      "familiar",
      "frente_praia",
      "hotel",
      "piscina",
      "praia",
      "rustico",
    ],
  },
  {
    category: "hotels",
    name: "Pousada Fazenda Caeiras",
    area: "praia",
    tags: ["4a_praia", "charme", "frente_praia", "pousada", "praia", "rustico"],
  },
  {
    category: "hotels",
    name: "Amendoeira Hotel",
    area: "praia",
    tags: [
      "1a_praia",
      "charme",
      "frente_praia",
      "hotel",
      "luxo",
      "praia",
      "premium",
      "rustico",
      "vista_mar",
    ],
  },
  {
    category: "hotels",
    name: "Pousada Natureza",
    area: "praia",
    tags: [
      "1a_praia",
      "familiar",
      "frente_praia",
      "piscina",
      "pousada",
      "praia",
      "vista_mar",
    ],
  },
  {
    category: "hotels",
    name: "Pousada dos Pássaros",
    area: "vila",
    tags: ["pousada", "vila"],
  },
  {
    category: "hotels",
    name: "Hotel Morro de São Paulo",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "hotel", "piscina", "praia"],
  },
  {
    category: "hotels",
    name: "Uma Janela para o Sol",
    area: "vila",
    tags: ["vila", "vista_mar"],
  },
  {
    category: "hotels",
    name: "Portaló",
    area: "vila",
    tags: ["piscina", "vila"],
  },
  {
    category: "hotels",
    name: "Pérola do Morro",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "piscina", "praia"],
  },
  {
    category: "hotels",
    name: "Safira do Morro",
    area: "praia",
    tags: [
      "1a_praia",
      "familiar",
      "frente_praia",
      "luxo",
      "piscina",
      "praia",
      "premium",
    ],
  },
  {
    category: "hotels",
    name: "Xerife Hotel",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "hotel", "praia"],
  },
  {
    category: "hotels",
    name: "Ilha da Saudade",
    area: "praia",
    tags: [
      "1a_praia",
      "frente_praia",
      "luxo",
      "piscina",
      "praia",
      "premium",
      "vista_mar",
    ],
  },
  {
    category: "hotels",
    name: "Porto dos Milagres",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "praia"],
  },
  {
    category: "hotels",
    name: "Passarte",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "praia"],
  },
  {
    category: "hotels",
    name: "Pousada da Praça",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "pousada", "praia"],
  },
  {
    category: "hotels",
    name: "Pousada Colibri",
    area: "vila",
    tags: ["piscina", "pousada", "vila", "vista_mar"],
  },
  {
    category: "hotels",
    name: "Pousada Porto de Cima",
    area: "vila",
    tags: ["pousada", "vila"],
  },
  {
    category: "hotels",
    name: "Vila Guaiamu",
    area: "praia",
    tags: ["3a_praia", "charme", "frente_praia", "praia", "rustico"],
  },
  {
    category: "hotels",
    name: "Villa dos Corais pousada",
    area: "praia",
    tags: ["4a_praia", "frente_praia", "piscina", "pousada", "praia"],
  },
  {
    category: "hotels",
    name: "Pousada Fazenda Caeira",
    area: "praia",
    tags: ["3a_praia", "charme", "frente_praia", "pousada", "praia", "rustico"],
  },
  { category: "hotels", name: "Hotel Anima", tags: ["hotel", "praia"] },
  {
    category: "hotels",
    name: "Vila dos Orixás Boutique Hotel & Spa",
    tags: ["hotel", "luxo", "praia", "premium"],
  },
  {
    category: "hotels",
    name: "Hotel Karapitangui",
    tags: ["hotel", "piscina", "praia"],
  },
  {
    category: "hotels",
    name: "Pousada Timbalada",
    area: "praia",
    tags: ["2a_praia", "economico", "frente_praia", "pousada", "praia"],
  },
  {
    category: "hotels",
    name: "Casa Celestino Residence",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "luxo", "praia", "premium"],
  },
  {
    category: "hotels",
    name: "Bahia Bacana Pousada",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "pousada", "praia"],
  },
  {
    category: "hotels",
    name: "Garapuá Praia Hotel",
    area: "garapua",
    tags: ["garapua", "hotel", "praia"],
  },
  {
    category: "hotels",
    name: "Hotel Morro da Saudade",
    area: "praia",
    tags: ["2a_praia", "frente_praia", "hotel", "piscina", "praia"],
  },
  {
    category: "hotels",
    name: "Bangalô dos sonhos",
    area: "praia",
    tags: ["frente_praia", "praia", "vista_mar"],
  },
  {
    category: "hotels",
    name: "Cantinho da Josete",
    area: "vila",
    tags: ["economico", "vila"],
  },
  {
    category: "hotels",
    name: "Vila Morro do Sao Paulo",
    area: "praia",
    tags: ["1a_praia", "frente_praia", "praia"],
  },
  { category: "hotels", name: "Casa Rossa", area: "vila", tags: ["vila"] },
  {
    category: "hotels",
    name: "Village Paraíso Tropical",
    area: "praia",
    tags: ["3a_praia", "frente_praia", "piscina", "praia"],
  },
  {
    category: "hotels",
    name: "Pousada do Encanto",
    area: "praia",
    tags: ["frente_praia", "pousada", "praia"],
  },
  {
    category: "hotels",
    name: "Hotel Vista Mar",
    area: "praia",
    tags: ["frente_praia", "hotel", "luxo", "praia", "premium", "vista_mar"],
  },
  {
    category: "shops",
    name: "Absolute",
    area: "praia",
    tags: ["bijuteria", "moda", "praia", "roupas"],
  },
  {
    category: "shops",
    name: "Local Brasil",
    area: "praia",
    tags: ["bijuteria", "moda", "praia", "roupas"],
  },
] as const;
