import type { SearchCatalogItem } from "./index.js";
import {
  morroV1SearchCatalogKey,
  morroV1SearchEnrichmentByKey,
} from "./morro-v1-search-enrichment.js";

export interface MorroV1SearchCatalogItem extends SearchCatalogItem {
  readonly latitude: number;
  readonly longitude: number;
  readonly category: string;
}

/**
 * Frozen projection of V1 `js/map/locations/locations.js` at
 * 60746fd7fed97b805758b37adfdbe3bad2582bfe.
 *
 * Frozen base discovery fields retained from the V1 canonical catalog:
 * category, canonical name, coordinates and aliases. Geographic eligibility
 * remains a resolver concern and is applied by `assistant-v1-place-boundary`.
 */
const morroV1SearchBaseCatalog: readonly MorroV1SearchCatalogItem[] =
  Object.freeze([
    {
      name: "Primeira Praia",
      latitude: -13.3776181,
      longitude: -38.9142193,
      category: "beaches",
      aliases: ["1a praia", "praia 1", "first beach"],
    },
    {
      name: "Praia de Garapuá",
      latitude: -13.4769538,
      longitude: -38.9165457,
      category: "beaches",
      aliases: ["garapua", "garapuá"],
    },
    {
      name: "Praia do Pôrto",
      latitude: -13.3876463,
      longitude: -38.9289298,
      category: "beaches",
      aliases: ["praia do porto", "porto"],
    },
    {
      name: "Praia da Gamboa",
      latitude: -13.3933118,
      longitude: -38.9367387,
      category: "beaches",
      aliases: ["gamboa"],
    },
    {
      name: "Segunda Praia",
      latitude: -13.3800508,
      longitude: -38.9118443,
      category: "beaches",
      aliases: ["2a praia", "praia 2", "second beach"],
    },
    {
      name: "Terceira Praia",
      latitude: -13.3839443,
      longitude: -38.9084472,
      category: "beaches",
      aliases: ["3a praia", "praia 3", "third beach"],
    },
    {
      name: "Quarta Praia",
      latitude: -13.3872014,
      longitude: -38.9052792,
      category: "beaches",
      aliases: ["4a praia", "praia 4", "fourth beach"],
    },
    {
      name: "Praia do Encanto",
      latitude: -13.4237732,
      longitude: -38.9059088,
      category: "beaches",
      aliases: [
        "quinta praia",
        "5a praia",
        "praia 5",
        "encanto",
        "fifth beach",
      ],
    },

    {
      name: "Morena Bela",
      latitude: -13.3787233,
      longitude: -38.917156,
      category: "restaurants",
    },
    {
      name: "Basílico",
      latitude: -13.3784237,
      longitude: -38.9168768,
      category: "restaurants",
      aliases: ["basilico"],
    },
    {
      name: "Ki Massa",
      latitude: -13.3776254,
      longitude: -38.9149403,
      category: "restaurants",
    },
    {
      name: "Tempeiro Caseiro",
      latitude: -13.3785007,
      longitude: -38.9165185,
      category: "restaurants",
    },
    {
      name: "Bizu",
      latitude: -13.3786053,
      longitude: -38.914091,
      category: "restaurants",
    },
    {
      name: "Six Club",
      latitude: -13.3807296,
      longitude: -38.9111405,
      category: "restaurants",
    },
    {
      name: "Recanto do Aviador",
      latitude: -13.3855501,
      longitude: -38.907413,
      category: "restaurants",
    },
    {
      name: "Branco&Negro",
      latitude: -13.3780582,
      longitude: -38.9165422,
      category: "restaurants",
    },
    {
      name: "Pedra Sobre Pedra",
      latitude: -13.3791779,
      longitude: -38.9126813,
      category: "restaurants",
    },
    {
      name: "Forno a Lenha de Mercedes",
      latitude: -13.3782428,
      longitude: -38.9167199,
      category: "restaurants",
      aliases: ["forno a lenha", "mercedes"],
    },
    {
      name: "Ponto G",
      latitude: -13.3779031,
      longitude: -38.9159823,
      category: "restaurants",
    },
    {
      name: "Ponto 9,99",
      latitude: -13.3776986,
      longitude: -38.9152394,
      category: "restaurants",
    },
    {
      name: "Patricia",
      latitude: -13.3796798,
      longitude: -38.9185071,
      category: "restaurants",
    },
    {
      name: "dizi 10",
      latitude: -13.3798625,
      longitude: -38.917681,
      category: "restaurants",
      aliases: ["dizi dez"],
    },
    {
      name: "Papoula",
      latitude: -13.3800138,
      longitude: -38.9176327,
      category: "restaurants",
    },
    {
      name: "Sabor da terra",
      latitude: -13.3779873,
      longitude: -38.9162855,
      category: "restaurants",
    },
    {
      name: "Santa Villa",
      latitude: -13.3803643,
      longitude: -38.912326,
      category: "restaurants",
    },
    {
      name: "Sambass",
      latitude: -13.3803168,
      longitude: -38.9120116,
      category: "restaurants",
    },
    {
      name: "Bar e Restaurante da Morena",
      latitude: -13.378306,
      longitude: -38.9153863,
      category: "restaurants",
    },
    {
      name: "Restaurante Alecrim",
      latitude: -13.3779464,
      longitude: -38.9160303,
      category: "restaurants",
    },
    {
      name: "Andina Cozinha Latina",
      latitude: -13.3792418,
      longitude: -38.9183595,
      category: "restaurants",
      aliases: ["andina"],
    },
    {
      name: "Restaurante da Creusa",
      latitude: -13.3990542,
      longitude: -39.0347146,
      category: "restaurants",
    },
    {
      name: "Papoula Culinária Artesanal",
      latitude: -13.3806731,
      longitude: -38.9176579,
      category: "restaurants",
    },
    {
      name: "Casa de Naná",
      latitude: -13.4747413,
      longitude: -38.9155208,
      category: "restaurants",
      aliases: ["nana"],
    },
    {
      name: "Kiosk da Valdete",
      latitude: -13.4748129,
      longitude: -38.9153706,
      category: "restaurants",
    },
    {
      name: "Capitão Pipoca",
      latitude: -13.4747535,
      longitude: -38.9152828,
      category: "restaurants",
      aliases: ["capitao pipoca"],
    },
    {
      name: "Barraca Nativa",
      latitude: -13.4745096,
      longitude: -38.914883,
      category: "restaurants",
    },
    {
      name: "Restaurant da Iracema",
      latitude: -13.4744398,
      longitude: -38.914731,
      category: "restaurants",
      aliases: ["iracema"],
    },
    {
      name: "Restaurante da Missi",
      latitude: -13.4744883,
      longitude: -38.9147971,
      category: "restaurants",
      aliases: ["missi"],
    },
    {
      name: "Minha Louca Paixão",
      latitude: -13.3811575,
      longitude: -38.9104565,
      category: "restaurants",
    },
    {
      name: "Restaurante da Cecinha",
      latitude: -13.4743298,
      longitude: -38.9144509,
      category: "restaurants",
      aliases: ["cecinha"],
    },
    {
      name: "Café das Artes",
      latitude: -13.3780708,
      longitude: -38.9168545,
      category: "restaurants",
      aliases: ["cafe das artes"],
    },
    {
      name: "Canoa",
      latitude: -13.383407,
      longitude: -38.9089515,
      category: "restaurants",
    },
    {
      name: "Restaurante do Francisco",
      latitude: -13.3903382,
      longitude: -38.9346791,
      category: "restaurants",
      aliases: ["francisco"],
    },
    {
      name: "La Tabla",
      latitude: -13.377844,
      longitude: -38.9153651,
      category: "restaurants",
    },
    {
      name: "Santa Luzia",
      latitude: -13.3827694,
      longitude: -38.9094546,
      category: "restaurants",
    },
    {
      name: "Chez Max",
      latitude: -13.3821402,
      longitude: -38.9098947,
      category: "restaurants",
    },
    {
      name: "Barraca da Miriam",
      latitude: -13.3994793,
      longitude: -38.9077185,
      category: "restaurants",
      aliases: ["miriam"],
    },
    {
      name: "O Casarão restaurante",
      latitude: -13.378336,
      longitude: -38.9170869,
      category: "restaurants",
      aliases: ["casarao", "casarão"],
    },
    {
      name: "Awa Mar",
      latitude: -13.3951051,
      longitude: -38.9077041,
      category: "restaurants",
    },
    {
      name: "Restaurante Pôr do Sol",
      latitude: -13.3904942,
      longitude: -38.9347432,
      category: "restaurants",
      aliases: ["por do sol"],
    },
    {
      name: "Restaurante da Piscina",
      latitude: -13.387321,
      longitude: -38.9054802,
      category: "restaurants",
    },
    {
      name: "Echoes Beach Club",
      latitude: -13.3899181,
      longitude: -38.9335985,
      category: "restaurants",
    },
    {
      name: "Restaurante Farol",
      latitude: -13.385,
      longitude: -38.919,
      category: "restaurants",
    },
    {
      name: "Sabores do Morro",
      latitude: -13.386,
      longitude: -38.92,
      category: "restaurants",
    },

    {
      name: "Hotel Fazenda Parque Praia Vila Guaiamu",
      latitude: -13.3873507,
      longitude: -38.9127277,
      category: "hotels",
      aliases: ["vila guaiamu hotel", "fazenda parque"],
    },
    {
      name: "Pousada Fazenda Caeiras",
      latitude: -13.3883252,
      longitude: -38.9061135,
      category: "hotels",
      aliases: ["fazenda caeiras"],
    },
    {
      name: "Amendoeira Hotel",
      latitude: -13.3778281,
      longitude: -38.9172358,
      category: "hotels",
      aliases: ["amendoeira"],
    },
    {
      name: "Pousada Natureza",
      latitude: -13.3775104,
      longitude: -38.9171534,
      category: "hotels",
    },
    {
      name: "Pousada dos Pássaros",
      latitude: -13.3795141,
      longitude: -38.9172535,
      category: "hotels",
      aliases: ["passaros"],
    },
    {
      name: "Hotel Morro de São Paulo",
      latitude: -13.3791591,
      longitude: -38.9166547,
      category: "hotels",
      aliases: ["hotel morro"],
    },
    {
      name: "Uma Janela para o Sol",
      latitude: -13.379541,
      longitude: -38.9170652,
      category: "hotels",
      aliases: ["janela para o sol"],
    },
    {
      name: "Portaló",
      latitude: -13.3775523,
      longitude: -38.9175756,
      category: "hotels",
      aliases: ["portalo"],
    },
    {
      name: "Pérola do Morro",
      latitude: -13.3781645,
      longitude: -38.9149192,
      category: "hotels",
      aliases: ["perola do morro"],
    },
    {
      name: "Safira do Morro",
      latitude: -13.3785061,
      longitude: -38.9156415,
      category: "hotels",
    },
    {
      name: "Xerife Hotel",
      latitude: -13.377789,
      longitude: -38.9172378,
      category: "hotels",
      aliases: ["xerife"],
    },
    {
      name: "Ilha da Saudade",
      latitude: -13.3783634,
      longitude: -38.9141991,
      category: "hotels",
    },
    {
      name: "Porto dos Milagres",
      latitude: -13.3785587,
      longitude: -38.9139954,
      category: "hotels",
    },
    {
      name: "Passarte",
      latitude: -13.3784605,
      longitude: -38.9167964,
      category: "hotels",
    },
    {
      name: "Pousada da Praça",
      latitude: -13.3784618,
      longitude: -38.916736,
      category: "hotels",
      aliases: ["pousada da praca"],
    },
    {
      name: "Pousada Colibri",
      latitude: -13.3810625,
      longitude: -38.919467,
      category: "hotels",
      aliases: ["colibri"],
    },
    {
      name: "Pousada Porto de Cima",
      latitude: -13.3798535,
      longitude: -38.9191331,
      category: "hotels",
      aliases: ["porto de cima"],
    },
    {
      name: "Vila Guaiamu",
      latitude: -13.3844636,
      longitude: -38.9095831,
      category: "hotels",
      aliases: ["guaiamu"],
    },
    {
      name: "Villa dos Corais pousada",
      latitude: -13.3866345,
      longitude: -38.9059675,
      category: "hotels",
      aliases: ["villa dos corais", "corais"],
    },
    {
      name: "Pousada Fazenda Caeira",
      latitude: -13.3858413,
      longitude: -38.9080274,
      category: "hotels",
      aliases: ["fazenda caeira"],
    },
    {
      name: "Hotel Anima",
      latitude: -13.4362563,
      longitude: -38.9015526,
      category: "hotels",
      aliases: ["anima"],
    },
    {
      name: "Vila dos Orixás Boutique Hotel & Spa",
      latitude: -13.4369703,
      longitude: -38.9014342,
      category: "hotels",
      aliases: ["vila dos orixas", "orixas"],
    },
    {
      name: "Hotel Karapitangui",
      latitude: -13.433198,
      longitude: -38.9028129,
      category: "hotels",
      aliases: ["karapitangui"],
    },
    {
      name: "Pousada Timbalada",
      latitude: -13.3812838,
      longitude: -38.9108804,
      category: "hotels",
      aliases: ["timbalada"],
    },
    {
      name: "Casa Celestino Residence",
      latitude: -13.3785577,
      longitude: -38.9154647,
      category: "hotels",
      aliases: ["celestino"],
    },
    {
      name: "Bahia Bacana Pousada",
      latitude: -13.3780883,
      longitude: -38.9146208,
      category: "hotels",
      aliases: ["bahia bacana"],
    },
    {
      name: "Garapuá Praia Hotel",
      latitude: -13.4745251,
      longitude: -38.9157128,
      category: "hotels",
      aliases: ["garapua hotel"],
    },
    {
      name: "Hotel Morro da Saudade",
      latitude: -13.3815967,
      longitude: -38.9115716,
      category: "hotels",
      aliases: ["morro da saudade"],
    },
    {
      name: "Bangalô dos sonhos",
      latitude: -13.3813335,
      longitude: -38.9230751,
      category: "hotels",
      aliases: ["bangalo dos sonhos"],
    },
    {
      name: "Cantinho da Josete",
      latitude: -13.3805442,
      longitude: -38.9176643,
      category: "hotels",
      aliases: ["josete"],
    },
    {
      name: "Vila Morro do Sao Paulo",
      latitude: -13.3771876,
      longitude: -38.9172992,
      category: "hotels",
      aliases: ["vila morro"],
    },
    {
      name: "Casa Rossa",
      latitude: -13.3839687,
      longitude: -38.9192849,
      category: "hotels",
    },
    {
      name: "Village Paraíso Tropical",
      latitude: -13.3829153,
      longitude: -38.9092912,
      category: "hotels",
      aliases: ["paraiso tropical"],
    },
    {
      name: "Pousada do Encanto",
      latitude: -13.387,
      longitude: -38.921,
      category: "hotels",
    },
    {
      name: "Hotel Vista Mar",
      latitude: -13.388,
      longitude: -38.922,
      category: "hotels",
    },

    {
      name: "Absolute",
      latitude: -13.3785049,
      longitude: -38.9142015,
      category: "shops",
    },
    {
      name: "Local Brasil",
      latitude: -13.3784357,
      longitude: -38.9141403,
      category: "shops",
    },
    {
      name: "Mercadinho Beira Mar",
      latitude: -13.4746186,
      longitude: -38.9161711,
      category: "shops",
    },
    {
      name: "Super Zimbo",
      latitude: -13.4044608,
      longitude: -38.9160512,
      category: "shops",
    },
    {
      name: "Mateus Esquadrais",
      latitude: -13.4046577,
      longitude: -38.915933,
      category: "shops",
    },
    {
      name: "São Pedro Imobiliária",
      latitude: -13.3825579,
      longitude: -38.9106646,
      category: "shops",
      aliases: ["sao pedro"],
    },
    {
      name: "Imóveis Brasil Bahia",
      latitude: -13.3789313,
      longitude: -38.9137477,
      category: "shops",
      aliases: ["imoveis brasil"],
    },
    {
      name: "Coruja",
      latitude: -13.3781062,
      longitude: -38.9166445,
      category: "shops",
    },
    {
      name: "Zimbo Dive",
      latitude: -13.3831358,
      longitude: -38.9091292,
      category: "shops",
      aliases: ["zimbo dive", "mergulho"],
    },
    {
      name: "Havaianas",
      latitude: -13.3782977,
      longitude: -38.9166961,
      category: "shops",
    },
    {
      name: "Loja Artesanato",
      latitude: -13.389,
      longitude: -38.923,
      category: "shops",
      aliases: ["artesanato"],
    },
    {
      name: "Farmácia Morro de São Paulo",
      latitude: -13.3785,
      longitude: -38.917,
      category: "shops",
      aliases: ["farmacia", "pharmacy", "remedio", "farmácia"],
    },

    {
      name: "Píer de Morro de São Paulo",
      latitude: -13.3769,
      longitude: -38.9137,
      category: "transport",
      aliases: ["pier", "porto", "cais", "embarque"],
    },
    {
      name: "Terminal Marítimo de Morro de São Paulo",
      latitude: -13.3772,
      longitude: -38.9139,
      category: "transport",
      aliases: ["terminal", "terminal maritimo", "catamaran"],
    },
    {
      name: "Ponto de Táxi Boat",
      latitude: -13.3781,
      longitude: -38.9144,
      category: "transport",
      aliases: ["taxi boat", "lancha", "barco"],
    },
    {
      name: "Ponto de Buggy e Transfer Local",
      latitude: -13.3794,
      longitude: -38.9172,
      category: "transport",
      aliases: ["buggy", "transfer local", "transfer"],
    },
    {
      name: "Agência de Passagens do Terminal",
      latitude: -13.3774,
      longitude: -38.9138,
      category: "transport",
      aliases: [
        "agencia de passagens",
        "agência de passagens",
        "bilheteria",
        "tickets",
        "catamaran tickets",
      ],
    },
    {
      name: "Agência de Transfer Marítimo",
      latitude: -13.3778,
      longitude: -38.9146,
      category: "transport",
      aliases: [
        "transfer maritimo",
        "transfer marítimo",
        "venda de passagens",
        "tickets office",
      ],
    },
    {
      name: "Cassi Turismo",
      latitude: -13.3775,
      longitude: -38.9135,
      category: "transport",
      aliases: [
        "cassi turismo",
        "cassi",
        "agencia cassi",
        "agência cassi",
        "passagens cassi",
        "transfer cassi",
      ],
    },
    {
      name: "Heliponto de Morro de São Paulo",
      latitude: -13.3814,
      longitude: -38.9098,
      category: "transport",
      aliases: ["heliponto", "helicoptero", "helicóptero"],
    },

    {
      name: "Farol do Morro",
      latitude: -13.375917,
      longitude: -38.9153479,
      category: "attractions",
      aliases: ["farol", "lighthouse"],
    },
    {
      name: "Toca do Morcego",
      latitude: -13.3766787,
      longitude: -38.9172057,
      category: "attractions",
      aliases: ["toca", "morcego"],
    },
    {
      name: "Mirante da Tirolesa",
      latitude: -13.376294,
      longitude: -38.9147974,
      category: "attractions",
      aliases: ["tirolesa", "mirante", "zipline"],
    },
    {
      name: "Fortaleza de Morro de São Paulo",
      latitude: -13.3742327,
      longitude: -38.9159466,
      category: "attractions",
      aliases: ["fortaleza", "forte", "tapirandú", "tapirandu", "fortress"],
    },
    {
      name: "Paredão da Argila",
      latitude: -13.3868816,
      longitude: -38.9282591,
      category: "attractions",
      aliases: ["paredao", "argila", "lama"],
    },
    {
      name: "Fonte Grande",
      latitude: -13.3795,
      longitude: -38.9185,
      category: "attractions",
      aliases: ["fonte", "cachoeira"],
    },
    {
      name: "Piscinas Naturais",
      latitude: -13.3855,
      longitude: -38.906,
      category: "attractions",
      aliases: ["piscina natural", "piscinas", "natural pools"],
    },
    {
      name: "Portal de Morro de São Paulo",
      latitude: -13.3768,
      longitude: -38.9178,
      category: "attractions",
      aliases: ["portal", "entrada", "gate"],
    },

    {
      name: "Toca do Morcego",
      latitude: -13.3766787,
      longitude: -38.9172057,
      category: "nightlife",
      aliases: ["toca", "morcego"],
    },
    {
      name: "Pulsar Club",
      latitude: -13.3802,
      longitude: -38.9118,
      category: "nightlife",
      aliases: ["pulsar"],
    },
    {
      name: "Mama Iate",
      latitude: -13.3804,
      longitude: -38.9115,
      category: "nightlife",
      aliases: ["mama"],
    },
    {
      name: "Sambass Bar",
      latitude: -13.3803168,
      longitude: -38.9120116,
      category: "nightlife",
      aliases: ["sambass"],
    },
    {
      name: "Luau na Segunda Praia",
      latitude: -13.38,
      longitude: -38.912,
      category: "nightlife",
      aliases: ["luau", "festa na praia", "beach party"],
    },

    {
      name: "Posto de Saúde de Morro de São Paulo",
      latitude: -13.3812,
      longitude: -38.9192,
      category: "emergencies",
      aliases: ["posto de saude", "hospital", "medico", "health center"],
    },
    {
      name: "Delegacia de Polícia",
      latitude: -13.381,
      longitude: -38.919,
      category: "emergencies",
      aliases: ["delegacia", "policia", "police"],
    },
    {
      name: "Farmácia Morro de São Paulo",
      latitude: -13.3785,
      longitude: -38.917,
      category: "emergencies",
      aliases: ["farmacia", "pharmacy", "remedio"],
    },
    {
      name: "Corpo de Bombeiros",
      latitude: -13.3808,
      longitude: -38.9185,
      category: "emergencies",
      aliases: ["bombeiros", "fire station", "bombeiro"],
    },

    {
      name: "Passeio de Barco Volta à Ilha",
      latitude: -13.3839443,
      longitude: -38.9084472,
      category: "tours",
      aliases: [
        "volta a ilha",
        "volta à ilha",
        "passeio de barco",
        "boat tour",
        "island tour",
      ],
    },
    {
      name: "Passeio para Garapuá",
      latitude: -13.4769538,
      longitude: -38.9165457,
      category: "tours",
      aliases: ["garapua tour", "passeio garapua"],
    },
    {
      name: "Trilha para a Gamboa",
      latitude: -13.3933118,
      longitude: -38.9367387,
      category: "tours",
      aliases: ["trilha gamboa", "caminhada gamboa", "hiking gamboa"],
    },
    {
      name: "Passeio de Quadriciclo",
      latitude: -13.3872014,
      longitude: -38.9052792,
      category: "tours",
      aliases: ["quadriciclo", "quad", "atv"],
    },
    {
      name: "Mergulho com Cilindro",
      latitude: -13.3831358,
      longitude: -38.9091292,
      category: "tours",
      aliases: ["mergulho", "diving", "scuba"],
    },
    {
      name: "Passeio de Caiaque",
      latitude: -13.3839443,
      longitude: -38.9084472,
      category: "tours",
      aliases: ["caiaque", "kayak", "canoagem"],
    },
  ]);

export const morroV1SearchCatalog: readonly MorroV1SearchCatalogItem[] =
  Object.freeze(
    morroV1SearchBaseCatalog.map((item) => {
      const enrichment = morroV1SearchEnrichmentByKey.get(
        morroV1SearchCatalogKey(item.category, item.name),
      );
      if (!enrichment) {
        throw new Error(
          `Missing V1 search enrichment for ${item.category}:${item.name}`,
        );
      }
      return Object.freeze({
        ...item,
        ...(enrichment.area ? { area: enrichment.area } : {}),
        ...(enrichment.tags ? { tags: enrichment.tags } : {}),
      });
    }),
  );
