export const morroV1SearchEnrichmentPart3 = [
  {"category":"shops","name":"Mercadinho Beira Mar","area":"garapua","tags":["alimentos","mercado","praia"]},
  {"category":"shops","name":"Super Zimbo","tags":["alimentos","mercado"]},
  {"category":"shops","name":"Mateus Esquadrais"},
  {"category":"shops","name":"São Pedro Imobiliária","area":"praia","tags":["praia"]},
  {"category":"shops","name":"Imóveis Brasil Bahia","area":"praia","tags":["praia"]},
  {"category":"shops","name":"Coruja","area":"praia","tags":["artesanato","praia","souvenir"]},
  {"category":"shops","name":"Zimbo Dive","area":"praia","tags":["praia"]},
  {"category":"shops","name":"Havaianas","area":"praia","tags":["praia"]},
  {"category":"shops","name":"Loja Artesanato","area":"praia","tags":["artesanato","praia","souvenir"]},
  {"category":"shops","name":"Farmácia Morro de São Paulo","area":"vila","tags":["farmacia"]},
  {"category":"transport","name":"Píer de Morro de São Paulo","area":"vila","tags":["porto","boat","transfer"]},
  {"category":"transport","name":"Terminal Marítimo de Morro de São Paulo","area":"vila","tags":["catamaran","boat","embarque"]},
  {"category":"transport","name":"Ponto de Táxi Boat","area":"vila","tags":["boat","taxi","transfer"]},
  {"category":"transport","name":"Ponto de Buggy e Transfer Local","area":"vila","tags":["buggy","transfer","taxi"]},
  {"category":"transport","name":"Agência de Passagens do Terminal","area":"vila","tags":["passagens","bilheteria","catamaran","ferry","boat","agencia"]},
  {"category":"transport","name":"Agência de Transfer Marítimo","area":"vila","tags":["passagens","transfer","agencia","boat","reserva"]},
  {"category":"transport","name":"Cassi Turismo","area":"vila","tags":["passagens","transfer","agencia","tickets","boat","cassi"]},
  {"category":"transport","name":"Heliponto de Morro de São Paulo","area":"vila","tags":["heliponto","helicoptero","aereo"]},
  {"category":"attractions","name":"Farol do Morro","area":"praia","tags":["cultural","historico"]},
  {"category":"attractions","name":"Toca do Morcego","area":"praia","tags":["mirante","sunset","vida_noturna"]},
  {"category":"attractions","name":"Mirante da Tirolesa","area":"praia","tags":["mirante","sunset"]},
  {"category":"attractions","name":"Fortaleza de Morro de São Paulo","area":"vila","tags":["cultural","historico"]},
  {"category":"attractions","name":"Paredão da Argila","tags":["natureza","praia","trilha"]},
  {"category":"attractions","name":"Fonte Grande","area":"vila","tags":["cultural","historico","natureza","trilha"]},
  {"category":"attractions","name":"Piscinas Naturais","area":"praia","tags":["mergulho","praia"]},
  {"category":"attractions","name":"Portal de Morro de São Paulo","area":"vila","tags":["praia","vida_noturna"]},
  {"category":"nightlife","name":"Toca do Morcego","area":"praia","tags":["mirante","sunset","vida_noturna"]},
  {"category":"nightlife","name":"Pulsar Club","area":"praia","tags":["balada","praia"]},
  {"category":"nightlife","name":"Mama Iate","area":"praia","tags":["praia"]},
  {"category":"nightlife","name":"Sambass Bar","area":"praia","tags":["bar","praia"]},
  {"category":"nightlife","name":"Luau na Segunda Praia","area":"praia","tags":["balada","musica_ao_vivo","praia"]},
  {"category":"emergencies","name":"Posto de Saúde de Morro de São Paulo","area":"vila","tags":["hospital","saude"]},
  {"category":"emergencies","name":"Delegacia de Polícia","area":"vila","tags":["policia"]},
  {"category":"emergencies","name":"Farmácia Morro de São Paulo","area":"praia","tags":["farmacia","hospital","saude"]},
  {"category":"emergencies","name":"Corpo de Bombeiros","area":"vila","tags":["bombeiros"]},
  {"category":"tours","name":"Passeio de Barco Volta à Ilha","area":"praia","tags":["barco","maritimo"]},
  {"category":"tours","name":"Passeio para Garapuá","area":"garapua","tags":["barco","maritimo","mergulho","snorkel"]},
  {"category":"tours","name":"Trilha para a Gamboa","tags":["aventura","trilha"]},
  {"category":"tours","name":"Passeio de Quadriciclo","area":"praia","tags":["atv","quadriciclo","trilha"]},
  {"category":"tours","name":"Mergulho com Cilindro","area":"praia","tags":["mergulho","snorkel"]},
  {"category":"tours","name":"Passeio de Caiaque","area":"praia","tags":["caiaque","fauna"]}
] as const;
