export const morroV1SearchEnrichmentPart1 = [
  {
    category: "beaches",
    name: "Primeira Praia",
    area: "praia",
    tags: [
      "1a_praia",
      "aventura",
      "mergulho",
      "piscina_natural",
      "snorkel",
      "surf",
    ],
  },
  {
    category: "beaches",
    name: "Praia de Garapuá",
    area: "garapua",
    tags: [
      "familiar",
      "garapua",
      "mergulho",
      "piscina_natural",
      "snorkel",
      "tranquila",
    ],
  },
  {
    category: "beaches",
    name: "Praia do Pôrto",
    tags: ["familiar", "mergulho", "snorkel", "tranquila"],
  },
  {
    category: "beaches",
    name: "Praia da Gamboa",
    tags: ["animada", "estrutura", "familiar", "gamboa", "tranquila"],
  },
  {
    category: "beaches",
    name: "Segunda Praia",
    area: "praia",
    tags: ["2a_praia", "animada", "estrutura", "piscina_natural"],
  },
  {
    category: "beaches",
    name: "Terceira Praia",
    area: "praia",
    tags: ["3a_praia", "familiar", "mergulho", "snorkel", "tranquila"],
  },
  {
    category: "beaches",
    name: "Quarta Praia",
    area: "praia",
    tags: ["4a_praia", "familiar", "piscina_natural", "sunset", "tranquila"],
  },
  {
    category: "beaches",
    name: "Praia do Encanto",
    tags: ["familiar", "sunset", "tranquila"],
  },
  {
    category: "restaurants",
    name: "Morena Bela",
    area: "vila",
    tags: ["baiana", "regional", "vila"],
  },
  {
    category: "restaurants",
    name: "Basílico",
    area: "vila",
    tags: ["italiana", "pizza", "romantico", "vila"],
  },
  {
    category: "restaurants",
    name: "Ki Massa",
    area: "vila",
    tags: ["familiar", "italiana", "pizza", "vila"],
  },
  {
    category: "restaurants",
    name: "Tempeiro Caseiro",
    area: "vila",
    tags: ["baiana", "familiar", "regional", "vila"],
  },
  { category: "restaurants", name: "Bizu", area: "vila", tags: ["vila"] },
  {
    category: "restaurants",
    name: "Six Club",
    area: "praia",
    tags: ["2a_praia", "animada", "bar", "praia"],
  },
  {
    category: "restaurants",
    name: "Recanto do Aviador",
    area: "praia",
    tags: ["3a_praia", "familiar", "frutos do mar", "praia"],
  },
  {
    category: "restaurants",
    name: "Branco&Negro",
    area: "vila",
    tags: ["casual", "moderno", "vila"],
  },
  {
    category: "restaurants",
    name: "Pedra Sobre Pedra",
    area: "praia",
    tags: [
      "2a_praia",
      "frutos do mar",
      "praia",
      "romantico",
      "seafood",
      "vista_mar",
    ],
  },
  {
    category: "restaurants",
    name: "Forno a Lenha de Mercedes",
    area: "vila",
    tags: ["artesanal", "italiana", "pizza", "vila"],
  },
  { category: "restaurants", name: "Ponto G", area: "vila", tags: ["vila"] },
  { category: "restaurants", name: "Ponto 9,99", area: "vila", tags: ["vila"] },
  { category: "restaurants", name: "Patricia", area: "vila", tags: ["vila"] },
  {
    category: "restaurants",
    name: "dizi 10",
    area: "vila",
    tags: ["baiana", "regional", "vila"],
  },
  {
    category: "restaurants",
    name: "Papoula",
    area: "vila",
    tags: ["saudavel", "vegetariano", "vila"],
  },
  {
    category: "restaurants",
    name: "Sabor da terra",
    area: "vila",
    tags: ["baiana", "regional", "vila"],
  },
  {
    category: "restaurants",
    name: "Santa Villa",
    area: "praia",
    tags: ["2a_praia", "frutos do mar", "praia", "romantico", "seafood"],
  },
  {
    category: "restaurants",
    name: "Sambass",
    area: "praia",
    tags: [
      "2a_praia",
      "animada",
      "bar",
      "beach_club",
      "frutos do mar",
      "praia",
      "seafood",
    ],
  },
  {
    category: "restaurants",
    name: "Bar e Restaurante da Morena",
    area: "vila",
    tags: ["baiana", "bar", "petisco", "regional", "vila"],
  },
  {
    category: "restaurants",
    name: "Restaurante Alecrim",
    area: "vila",
    tags: ["baiana", "regional", "vila"],
  },
  {
    category: "restaurants",
    name: "Andina Cozinha Latina",
    area: "vila",
    tags: ["latina", "vila"],
  },
  {
    category: "restaurants",
    name: "Restaurante da Creusa",
    area: "caminho",
    tags: ["baiana", "caminho", "regional"],
  },
  {
    category: "restaurants",
    name: "Papoula Culinária Artesanal",
    area: "vila",
    tags: ["saudavel", "vegetariano", "vila"],
  },
  {
    category: "restaurants",
    name: "Casa de Naná",
    area: "garapua",
    tags: [
      "baiana",
      "frutos do mar",
      "garapua",
      "praia",
      "regional",
      "seafood",
    ],
  },
  {
    category: "restaurants",
    name: "Kiosk da Valdete",
    area: "garapua",
    tags: ["bar", "beach_club", "garapua", "petisco", "praia", "quiosque"],
  },
  {
    category: "restaurants",
    name: "Capitão Pipoca",
    area: "garapua",
    tags: ["bar", "garapua", "petisco", "praia"],
  },
  {
    category: "restaurants",
    name: "Barraca Nativa",
    area: "garapua",
    tags: [
      "baiana",
      "bar",
      "frutos do mar",
      "garapua",
      "petisco",
      "praia",
      "quiosque",
      "regional",
      "seafood",
    ],
  },
  {
    category: "restaurants",
    name: "Restaurant da Iracema",
    area: "garapua",
    tags: [
      "baiana",
      "frutos do mar",
      "garapua",
      "praia",
      "regional",
      "seafood",
    ],
  },
  {
    category: "restaurants",
    name: "Restaurante da Missi",
    area: "garapua",
    tags: [
      "baiana",
      "frutos do mar",
      "garapua",
      "praia",
      "regional",
      "seafood",
    ],
  },
  {
    category: "restaurants",
    name: "Minha Louca Paixão",
    area: "praia",
    tags: ["2a_praia", "praia", "romantico"],
  },
  {
    category: "restaurants",
    name: "Restaurante da Cecinha",
    area: "garapua",
    tags: [
      "baiana",
      "frutos do mar",
      "garapua",
      "praia",
      "regional",
      "seafood",
    ],
  },
  {
    category: "restaurants",
    name: "Café das Artes",
    area: "vila",
    tags: ["cafe", "vila"],
  },
  {
    category: "restaurants",
    name: "Canoa",
    area: "praia",
    tags: ["3a_praia", "frutos do mar", "praia", "seafood"],
  },
  {
    category: "restaurants",
    name: "Restaurante do Francisco",
    area: "caminho",
    tags: ["caminho"],
  },
  { category: "restaurants", name: "La Tabla", area: "vila", tags: ["vila"] },
  {
    category: "restaurants",
    name: "Santa Luzia",
    area: "praia",
    tags: ["3a_praia", "frutos do mar", "praia", "romantico", "seafood"],
  },
  {
    category: "restaurants",
    name: "Chez Max",
    area: "praia",
    tags: ["3a_praia", "frutos do mar", "praia", "romantico", "seafood"],
  },
] as const;
