#!/bin/sh
set -eu

required_keys="MYSQL_ROOT_PASSWORD AUTH_DATABASE_NAME AUTH_DATABASE_USER AUTH_DATABASE_PASSWORD ORDERING_DATABASE_NAME ORDERING_DATABASE_USER ORDERING_DATABASE_PASSWORD FINANCIAL_DATABASE_NAME FINANCIAL_DATABASE_USER FINANCIAL_DATABASE_PASSWORD AFFILIATES_DATABASE_NAME AFFILIATES_DATABASE_USER AFFILIATES_DATABASE_PASSWORD"

for key in $required_keys; do
  value="$(printenv "$key" 2>/dev/null || true)"
  if [ -z "$value" ]; then
    echo "staging-mysql-init: missing required environment variable: $key" >&2
    exit 1
  fi
done

identifier_keys="AUTH_DATABASE_NAME AUTH_DATABASE_USER ORDERING_DATABASE_NAME ORDERING_DATABASE_USER FINANCIAL_DATABASE_NAME FINANCIAL_DATABASE_USER AFFILIATES_DATABASE_NAME AFFILIATES_DATABASE_USER"
for key in $identifier_keys; do
  value="$(printenv "$key")"
  case "$value" in
    *[!A-Za-z0-9_]*)
      echo "staging-mysql-init: invalid SQL identifier in $key" >&2
      exit 1
      ;;
  esac
done

password_keys="MYSQL_ROOT_PASSWORD AUTH_DATABASE_PASSWORD ORDERING_DATABASE_PASSWORD FINANCIAL_DATABASE_PASSWORD AFFILIATES_DATABASE_PASSWORD"
for key in $password_keys; do
  value="$(printenv "$key")"
  case "$value" in
    *"'"*|*"\\"*)
      echo "staging-mysql-init: $key contains unsupported SQL-string characters" >&2
      exit 1
      ;;
  esac
done

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${AUTH_DATABASE_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${AUTH_DATABASE_USER}'@'%' IDENTIFIED BY '${AUTH_DATABASE_PASSWORD}';
ALTER USER '${AUTH_DATABASE_USER}'@'%' IDENTIFIED BY '${AUTH_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${AUTH_DATABASE_NAME}\`.* TO '${AUTH_DATABASE_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${ORDERING_DATABASE_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${ORDERING_DATABASE_USER}'@'%' IDENTIFIED BY '${ORDERING_DATABASE_PASSWORD}';
ALTER USER '${ORDERING_DATABASE_USER}'@'%' IDENTIFIED BY '${ORDERING_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${ORDERING_DATABASE_NAME}\`.* TO '${ORDERING_DATABASE_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${FINANCIAL_DATABASE_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${FINANCIAL_DATABASE_USER}'@'%' IDENTIFIED BY '${FINANCIAL_DATABASE_PASSWORD}';
ALTER USER '${FINANCIAL_DATABASE_USER}'@'%' IDENTIFIED BY '${FINANCIAL_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${FINANCIAL_DATABASE_NAME}\`.* TO '${FINANCIAL_DATABASE_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${AFFILIATES_DATABASE_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '${AFFILIATES_DATABASE_USER}'@'%' IDENTIFIED BY '${AFFILIATES_DATABASE_PASSWORD}';
ALTER USER '${AFFILIATES_DATABASE_USER}'@'%' IDENTIFIED BY '${AFFILIATES_DATABASE_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${AFFILIATES_DATABASE_NAME}\`.* TO '${AFFILIATES_DATABASE_USER}'@'%';

FLUSH PRIVILEGES;
SQL

echo "staging-mysql-init: schemas and least-privilege users initialized"
