import test from 'node:test';import assert from 'node:assert/strict';
import {createSavedPlacesService} from '../src/service.mjs';
import {guestStorageKey,createGuestPayload} from '../src/identity.mjs';
const D='morro-de-sao-paulo', I='itacare';
const a={destinationId:D,placeId:'p1',name:'Segunda Praia',category:'Praias'},b={...a,placeId:'p2',name:'Toca do Morcego'};
const makeStore=()=>{const data=new Map();return {getItem:key=>data.get(key)??null,setItem:(key,v)=>data.set(key,v),removeItem:key=>data.delete(key),data};};
const create=(extra={})=>createSavedPlacesService({destinationId:D,guestSimulation:true,...extra});
test('initial visitor list empty, no synthetic favorites',async()=>{const s=create();assert.equal((await s.refresh()).status,'empty');assert.equal(s.snapshot().items.length,0);});
test('same collection broadcasts to two independent UI subscribers',async()=>{const s=create(),one=[],two=[];s.subscribe(x=>one.push(x.items.length));s.subscribe(x=>two.push(x.items.length));await s.add(a);await s.add(b);await s.remove(a);assert.deepEqual(one,two);assert.equal(two.at(-1),1);});
test('duplicate same canonical identity idempotent',async()=>{const s=create();await s.add(a);const revision=s.snapshot().revision;await s.add({...a,name:'Renamed'});assert.equal(s.snapshot().revision,revision);assert.equal(s.snapshot().items.length,1);});
test('removal unknown ID idempotent',async()=>{const s=create();await s.add(a);const old=s.snapshot().revision;await s.remove({...a,placeId:'unknown'});assert.equal(s.snapshot().revision,old);});
test('cross destination add rejected before side effects',async()=>{const s=create();await assert.rejects(s.add({...a,destinationId:I}));assert.equal(s.snapshot().items.length,0);});
test('destinations never share a guest favorite list',async()=>{const s=create();await s.add(a);await s.switchDestination(I);assert.equal(s.snapshot().items.length,0);await s.add({destinationId:I,placeId:'resende',name:'Resende'});await s.switchDestination(D);assert.equal(s.snapshot().items.length,1);assert.equal(s.snapshot().items[0].placeId,'p1');});
test('local guest offline can retain session entries without fake server authority',async()=>{const s=create();s.setOnline(false);await s.add(a);assert.equal(s.snapshot().status,'ready');assert.equal(s.snapshot().ownerVerified,false);assert.equal(s.snapshot().online,false);});
test('without consent never touches provided storage',async()=>{const store={getItem(){throw Error('NOT_ALLOWED')},setItem(){throw Error('NOT_ALLOWED')}};const s=create({storage:store,persistenceConsent:false});await s.add(a);assert.equal(s.snapshot().items.length,1);});
test('with explicit consent destination-local payload survives service reinitialization',async()=>{const store=makeStore();const s=create({storage:store,persistenceConsent:true});await s.add(a);const next=create({storage:store,persistenceConsent:true});await next.refresh();assert.equal(next.snapshot().items[0].placeId,'p1');assert.equal(store.data.size,1);});
test('storage write error does not commit false favorite or revision',async()=>{const store={getItem:()=>null,setItem(){throw Error('QUOTA')}};const s=create({storage:store,persistenceConsent:true});await s.add(a);assert.equal(s.snapshot().status,'error');assert.equal(s.snapshot().items.length,0);assert.equal(s.snapshot().revision,0);});
test('corrupt storage never silently erased',async()=>{const store=makeStore();store.data.set(guestStorageKey(D),'{notjson');const s=create({storage:store,persistenceConsent:true});await s.refresh();assert.equal(s.snapshot().status,'error');assert.equal(store.data.get(guestStorageKey(D)),'{notjson');await s.add(a);assert.equal(s.snapshot().items.length,0);});
test('storage events update other tab on newer revision only',async()=>{const store=makeStore();const one=create({storage:store,persistenceConsent:true});await one.refresh();await one.add(a);const two=create({storage:store,persistenceConsent:true});await two.refresh();await one.add(b);two.importGuestStorageEvent({key:guestStorageKey(D),newValue:store.data.get(guestStorageKey(D))});assert.equal(two.snapshot().items.length,2);});
test('storage events ignore other destination',async()=>{const store=makeStore(),s=create({storage:store,persistenceConsent:true});await s.refresh();s.importGuestStorageEvent({key:guestStorageKey(I),newValue:createGuestPayload(I,5,[{destinationId:I,placeId:'p2',name:'Resende'}])});assert.equal(s.snapshot().items.length,0);});
test('same revision conflicting tab writes require user review',async()=>{const store=makeStore(),s=create({storage:store,persistenceConsent:true});await s.refresh();await s.add(a);s.importGuestStorageEvent({key:guestStorageKey(D),newValue:createGuestPayload(D,1,[b])});assert.equal(s.snapshot().status,'conflict');await s.add(b);assert.equal(s.snapshot().status,'conflict');});
test('malformed storage events ignored, not erased',async()=>{const store=makeStore(),s=create({storage:store,persistenceConsent:true});await s.refresh();s.importGuestStorageEvent({key:guestStorageKey(D),newValue:'{'});assert.equal(s.snapshot().items.length,0);});
test('subscription unsubscribe stops events',async()=>{const s=create(),calls=[];const off=s.subscribe(x=>calls.push(x));off();await s.add(a);assert.equal(calls.length,1);});
test('public snapshots immutable',async()=>{const s=create();await s.add(a);assert.throws(()=>s.snapshot().items.push(a));assert.throws(()=>s.snapshot().items[0].name='x');});
test('stale consented guest tab cannot overwrite a newer persisted revision',async()=>{
 const store=makeStore();
 const stale=create({storage:store,persistenceConsent:true});
 const current=create({storage:store,persistenceConsent:true});
 await stale.refresh();await current.refresh();
 await current.add(a);
 const before=store.data.get(guestStorageKey(D));
 await stale.add(b);
 assert.equal(stale.snapshot().status,'conflict');
 assert.equal(stale.snapshot().items.length,0);
 assert.equal(store.data.get(guestStorageKey(D)),before);
});
test('guest tab refuses resurrecting favorites silently removed in another tab',async()=>{
 const store=makeStore();const first=create({storage:store,persistenceConsent:true});
 await first.add(a);store.data.delete(guestStorageKey(D));
 await first.add(b);
 assert.equal(first.snapshot().status,'conflict');assert.equal(store.data.size,0);
});
