import test from 'node:test';import assert from 'node:assert/strict';
import {destinationIdOf,placeIdOf,safeText,normalizeSavedItem,normalizeSavedList,parseGuestPayload,createGuestPayload,guestStorageKey,P08_MAX_ITEMS} from '../src/identity.mjs';
const D='morro-de-sao-paulo';
const sample={destinationId:D,placeId:'demo-segunda-praia',name:'Segunda Praia',category:'Praias'};
for (const invalid of ['',null,undefined,' /etc','invalid/slug','✈️']) test('invalid destination rejected: '+String(invalid),()=>assert.throws(()=>destinationIdOf(invalid)));
test('canonical ID required, not human display name',()=>assert.throws(()=>placeIdOf('Segunda Praia')));
test('canonical ID accepts UUID-shaped slug',()=>assert.equal(placeIdOf('843c2b1a-1a08-4aaa-9933-123abc454fbd'),'843c2b1a-1a08-4aaa-9933-123abc454fbd'));
test('unsafe/control text bounded',()=>assert.equal(safeText('ab\u0000cd',4),'abcd'));
test('same place cannot be saved to other destination',()=>assert.throws(()=>normalizeSavedItem(sample,'itacare')));
test('same ID deduplicates list',()=>assert.equal(normalizeSavedList([sample,sample],D).length,1));
test('strict item rejects empty and invalid names',()=>assert.throws(()=>normalizeSavedItem({...sample,name:''},D)));
test('list strict malformed coordinates irrelevant, identity only',()=>assert.equal(normalizeSavedItem({...sample,lat:'invalid'},D).placeId,sample.placeId));
test('bound number of saved places',()=>assert.throws(()=>normalizeSavedList(Array.from({length:P08_MAX_ITEMS+1},(_,i)=>({...sample,placeId:'p'+i})),D)));
test('guest schema roundtrip',()=>{const parsed=parseGuestPayload(createGuestPayload(D,2,[sample]),D);assert.equal(parsed.items[0].name,'Segunda Praia');assert.equal(parsed.revision,2);});
test('other destination persisted payload denied',()=>assert.throws(()=>parseGuestPayload(createGuestPayload(D,2,[sample]),'itacare')));
test('invalid JSON never becomes favorites',()=>assert.throws(()=>parseGuestPayload('{bad',D)));
test('invalid schema version rejected',()=>assert.throws(()=>parseGuestPayload(JSON.stringify({schemaVersion:2,destinationId:D,revision:2,items:[]}),D)));
test('unbounded payload rejected',()=>assert.throws(()=>parseGuestPayload(' '.repeat(55001),D)));
test('guest storage key scoped by destination',()=>assert.notEqual(guestStorageKey(D),guestStorageKey('itacare')));
