#!/bin/sh
set -eu

required_keys="MYSQL_ROOT_PASSWORD AUTH_DATABASE_NAME AUTH_DATABASE_USER AUTH_DATABASE_PASSWORD AUDIT_DATABASE_NAME AUDIT_DATABASE_USER AUDIT_DATABASE_PASSWORD DESTINATIONS_DATABASE_NAME DESTINATIONS_DATABASE_USER DESTINATIONS_DATABASE_PASSWORD CONTENT_DATABASE_NAME CONTENT_DATABASE_USER CONTENT_DATABASE_PASSWORD BUSINESS_DATABASE_NAME BUSINESS_DATABASE_USER BUSINESS_DATABASE_PASSWORD ORDERING_DATABASE_NAME ORDERING_DATABASE_USER ORDERING_DATABASE_PASSWORD FINANCIAL_DATABASE_NAME FINANCIAL_DATABASE_USER FINANCIAL_DATABASE_PASSWORD TICKETING_DATABASE_NAME TICKETING_DATABASE_USER TICKETING_DATABASE_PASSWORD NOTIFICATIONS_DATABASE_NAME NOTIFICATIONS_DATABASE_USER NOTIFICATIONS_DATABASE_PASSWORD AFFILIATES_DATABASE_NAME AFFILIATES_DATABASE_USER AFFILIATES_DATABASE_PASSWORD ANALYTICS_DATABASE_NAME ANALYTICS_DATABASE_USER ANALYTICS_DATABASE_PASSWORD CRM_DATABASE_NAME CRM_DATABASE_USER CRM_DATABASE_PASSWORD COMMERCE_DATABASE_NAME COMMERCE_DATABASE_USER COMMERCE_DATABASE_PASSWORD"

for key in $required_keys; do
  value="$(printenv "$key" 2>/dev/null || true)"
  if [ -z "$value" ]; then
    echo "production-mysql-init: missing required environment variable: $key" >&2
    exit 1
  fi
done

identifier_keys="AUTH_DATABASE_NAME AUTH_DATABASE_USER AUDIT_DATABASE_NAME AUDIT_DATABASE_USER DESTINATIONS_DATABASE_NAME DESTINATIONS_DATABASE_USER CONTENT_DATABASE_NAME CONTENT_DATABASE_USER BUSINESS_DATABASE_NAME BUSINESS_DATABASE_USER ORDERING_DATABASE_NAME ORDERING_DATABASE_USER FINANCIAL_DATABASE_NAME FINANCIAL_DATABASE_USER TICKETING_DATABASE_NAME TICKETING_DATABASE_USER NOTIFICATIONS_DATABASE_NAME NOTIFICATIONS_DATABASE_USER AFFILIATES_DATABASE_NAME AFFILIATES_DATABASE_USER ANALYTICS_DATABASE_NAME ANALYTICS_DATABASE_USER CRM_DATABASE_NAME CRM_DATABASE_USER COMMERCE_DATABASE_NAME COMMERCE_DATABASE_USER"

for key in $identifier_keys; do
  value="$(printenv "$key")"
  case "$value" in
    *[!A-Za-z0-9_]*)
      echo "production-mysql-init: invalid SQL identifier in $key" >&2
      exit 1
      ;;
  esac
done

sql_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e "s/'/''/g"
}

provision_domain() {
  database="$1"
  user="$2"
  password="$(sql_escape "$3")"
  mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" <<SQL
CREATE DATABASE IF NOT EXISTS \`$database\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE USER IF NOT EXISTS '$user'@'%' IDENTIFIED BY '$password';
ALTER USER '$user'@'%' IDENTIFIED BY '$password';
GRANT ALL PRIVILEGES ON \`$database\`.* TO '$user'@'%';
SQL
  echo "production-mysql-init: owner ready: $database -> $user"
}

provision_domain "$AUTH_DATABASE_NAME" "$AUTH_DATABASE_USER" "$AUTH_DATABASE_PASSWORD"
provision_domain "$AUDIT_DATABASE_NAME" "$AUDIT_DATABASE_USER" "$AUDIT_DATABASE_PASSWORD"
provision_domain "$DESTINATIONS_DATABASE_NAME" "$DESTINATIONS_DATABASE_USER" "$DESTINATIONS_DATABASE_PASSWORD"
provision_domain "$CONTENT_DATABASE_NAME" "$CONTENT_DATABASE_USER" "$CONTENT_DATABASE_PASSWORD"
provision_domain "$BUSINESS_DATABASE_NAME" "$BUSINESS_DATABASE_USER" "$BUSINESS_DATABASE_PASSWORD"
provision_domain "$ORDERING_DATABASE_NAME" "$ORDERING_DATABASE_USER" "$ORDERING_DATABASE_PASSWORD"
provision_domain "$FINANCIAL_DATABASE_NAME" "$FINANCIAL_DATABASE_USER" "$FINANCIAL_DATABASE_PASSWORD"
provision_domain "$TICKETING_DATABASE_NAME" "$TICKETING_DATABASE_USER" "$TICKETING_DATABASE_PASSWORD"
provision_domain "$NOTIFICATIONS_DATABASE_NAME" "$NOTIFICATIONS_DATABASE_USER" "$NOTIFICATIONS_DATABASE_PASSWORD"
provision_domain "$AFFILIATES_DATABASE_NAME" "$AFFILIATES_DATABASE_USER" "$AFFILIATES_DATABASE_PASSWORD"
provision_domain "$ANALYTICS_DATABASE_NAME" "$ANALYTICS_DATABASE_USER" "$ANALYTICS_DATABASE_PASSWORD"
provision_domain "$CRM_DATABASE_NAME" "$CRM_DATABASE_USER" "$CRM_DATABASE_PASSWORD"
provision_domain "$COMMERCE_DATABASE_NAME" "$COMMERCE_DATABASE_USER" "$COMMERCE_DATABASE_PASSWORD"

mysql --protocol=socket -uroot -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;"
echo "production-mysql-init: 13 canonical schemas and least-privilege owners initialized"
